# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19snKd7PWUlV9zefGhOIa2KdfgtE3PM0f
"""

p=3.14
r=12
2*p*r

E="ELÇİN"
E[2:4]

E="bal arıları uçarken"
E[1:23:2]
#:2 ne kadar atlanacağını söyler

E="bal arıları uçarken"
E[::-1]
len(E)
#tersten yazdırır
#uzunluğu bulmak "len()""

a="kumsalda"
b=" yürümek"
c=" güzeldir    "
(a+b+c)*3

a=3232
b=str(a)
b
#str ifadeyi stringe çevirir

a="56556.32"
c=float(a)
c

print("Hello World")

# "\n" alt alta yazdırır
# "\t" bir tab boşluk bırakarak yazar
print(" yazılımı \n çok \t seviyorum \n pozitif")
type

# type() fonksiyonun tipini söyler
t="654.546"
r=float(t)
w=int(r)

type(w)

b=6546.64
print(type(b))

print("gül",3,1,8,sep="\n")

print(*"bal","cal",*"dal",56,65,sep="\n")

print("{2} {0} {1}".format(11,22,33))

print("{2} {1} {0}".format(1,5,4))